Repository DSC-RSU/DSC-RSU-Website, pull requests merged in 2020-10, with the labels that each got.

#20 Updates on navbar
  AboutUS.html
  contactUs.html
  css/index.css
  gallery.html
  index.html
  projects.html
  teams.html
Labels: Ready-to-merge

#21 Added 'go-to-top' scroller in all pages
  AboutUS.html
  contactUs.html
  css/AboutUS.css
  css/contactUs.css
  css/gallery.css
  css/index.css
  css/projects.css
  css/teams.css
  gallery.html
  index.html
  js/AboutUS.js
  js/contactUs.js
  js/gallery.js
  js/index.js
  js/jquery/jquery-3.5.0.js
  js/jquery/jqueryscrolldetector.js
  js/projects.js
  js/teams.js
  projects.html
  teams.html
Labels: Ready-to-merge

#23 docs: format of pull request
  docs/pull-request.md
Labels: Ready-to-merge

#27 added images and edited teams.html
  css/teams.css
  imgs/BACK_END1.png
  imgs/BACK_END2.png
  imgs/BACK_END3.PNG
  imgs/CORE_TEAM.png
  imgs/CYBER_SEC.png
  imgs/DESIGN.png
  imgs/DSC_LOGO.png
  imgs/FOOTER.jpeg
  imgs/FRONT_END1.png
  imgs/FRONT_END2.PNG
  imgs/HEAD.jpg
  imgs/MANAGEMENT.png
  imgs/SMPR.png
  teams.html
Labels: hacktoberfest-accepted

#22 Add Footer to all pages
  contactUs.html
  css/bootstrap.css
  css/bootstrap.min.css
  css/footer.css
  gallery.html
  index.html
  projects.html
  teams.html
Labels: Ready-to-merge

#29 Edited Home Page
  css/index.css
  index.html
Labels: Ready-to-merge, hacktoberfest-accepted

#34 fixed navbar
  contactUs.html
  css/AboutUS.css
  css/contactUs.css
  css/gallery.css
  css/index.css
  css/projects.css
  css/teams.css
  gallery.html
  index.html
  projects.html
  teams.html
Labels: Ready-to-merge, hacktoberfest-accepted

#37 Added badges in readme.
  README.md
Labels: hacktoberfest-accepted

#39 'go-to-top' button in footer
  contactUs.html
  gallery.html
  index.html
  projects.html
  teams.html
Labels: hacktoberfest-accepted

#42 Added title in projects.html, Contactus.html, gallery.html
  contactUs.html
  css/contactUs.css
  css/gallery.css
  css/projects.css
  gallery.html
  imgs/contactus.jpg
  imgs/gallery.jpg
  imgs/puzzle.jpg
  projects.html
Labels: hacktoberfest-accepted

#45 Modified Button
  contactUs.html
  css/contactUs.css
  css/gallery.css
  css/index.css
  css/projects.css
  css/teams.css
  gallery.html
  index.html
  projects.html
  teams.html
Labels: hacktoberfest-accepted

#49 Fixed #41 #11 ContactUs page and Footer
  README.md
  contactUs.html
  css/contact.css
  css/footer.css
  css/gallery.css
  css/index.css
  gallery.html
  imgs/back.jpg
  imgs/facebook.jpg
  imgs/gallery/ppl1.jpg
  imgs/gallery/ppl2.jpg
  imgs/gallery/ppl3.jpg
  imgs/gallery/ppl4.jpg
  imgs/gallery/ppl5.jpg
  imgs/instagram.jpg
  imgs/linkedin.jpg
  imgs/main.jpg
  imgs/twitter.jpg
  index.html
  projects.html
  teams.html
Labels: hacktoberfest-accepted

#50 #41 changes in footer and Contact us page
  contactUs.html
Labels: hacktoberfest-accepted
